### ISSUE TITLE
"ZMQError: Interrupted system call" in a multi-process environment

### ISSUE THREAD

**Issue by Pastafarianist** [arskom/spyne#456]
First of all, many thanks for such a versatile product!

I have stumbled upon a weird crash in a basic RPC service. It is supposed to listen for a signal on a ZeroMQ socket, and as soon as it receives one, the server should shut down. The server is launched as a separate process. Within that process, the requests are processed in a separate thread.

Here is the code:

```python
import threading, multiprocessing, time, Queue

from spyne import MethodContext
from spyne.application import Application
from spyne.service import ServiceBase
from spyne.decorator import rpc
from spyne.protocol.msgpack import MessagePackRpc
from spyne.client.zeromq import ZeroMQClient
from spyne.auxproc import process_contexts
from spyne.server.zeromq import ZeroMQServer, ZmqMethodContext


# <... code for StoppableZeroMQServer goes here ...>


class RPCService(ServiceBase):
    @rpc()
    def stop(ctx):
        ctx.udc.queue.put("STOPPING!!")


rpc_app = Application(
    [RPCService],
    tns='myrpc',
    in_protocol=MessagePackRpc(validator='soft'),
    out_protocol=MessagePackRpc()
)


class RPCServer(threading.Thread):
    def __init__(self, rpc_address):
        super(RPCServer, self).__init__(name='RPC server thread')
        self.queue = Queue.Queue()

        # The following is black magic to allow access to RPCServer
        # from RPCService via ctx.udc.
        def on_method_call(ctx):
            ctx.udc = self
        rpc_app.event_manager.add_listener('method_call', on_method_call)

        self.rpc_server = StoppableZeroMQServer(rpc_app, rpc_address)

    def run(self):
        while True:
            print('serving')
            self.rpc_server.serve_once()
            try:
                # in the worst case we're polling the queue 10 times per second
                msg = self.queue.get(block=True, timeout=0.1)
                if msg == "STOPPING!!":
                    break
            except Queue.Empty:
                pass


class RPCClient(ZeroMQClient):
    def __init__(self, rpc_address):
        super(RPCClient, self).__init__(rpc_address, rpc_app)


class WrapperProcess(multiprocessing.Process):
    def __init__(self, rpc_address):
        super(WrapperProcess, self).__init__(name='Wrapper process')
        self.rpc_server = RPCServer(rpc_address)

    def run(self):
        self.rpc_server.start()
        self.rpc_server.join()


def test_rpc_stop():
    rpc_address = 'tcp://127.0.0.1:4005'

    proc = WrapperProcess(rpc_address)
    client = RPCClient(rpc_address)

    proc.start()
    time.sleep(1)

    client.service.stop()
    time.sleep(1)

    assert not proc.is_alive()

test_rpc_stop()
```

The code depends on `StoppableZeroMQServer`. **It is basically copy-pasted from Spyne sources** but modified to not block forever. Here it is:

```python
class StoppableZeroMQServer(ZeroMQServer):
    def __init__(self, *args, **kwargs):
        super(StoppableZeroMQServer, self).__init__(*args, **kwargs)

    def serve_once(self):
        # The following is a copy-pasta from the Spyne sources.
        error = None

        initial_ctx = ZmqMethodContext(self)
        initial_ctx.in_string = [self.zmq_socket.recv()]

        contexts = self.generate_contexts(initial_ctx)
        p_ctx, others = contexts[0], contexts[1:]
        if p_ctx.in_error:
            p_ctx.out_object = p_ctx.in_error
            error = p_ctx.in_error

        else:
            self.get_in_object(p_ctx)

            if p_ctx.in_error:
                p_ctx.out_object = p_ctx.in_error
                error = p_ctx.in_error
            else:
                self.get_out_object(p_ctx)
                if p_ctx.out_error:
                    p_ctx.out_object = p_ctx.out_error
                    error = p_ctx.out_error

        self.get_out_string(p_ctx)

        process_contexts(self, others, error)

        self.zmq_socket.send(''.join(p_ctx.out_string))

        p_ctx.close()
```

Running this code produces the following error:

```
serving
Exception in thread RPC server thread:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/path/to/file/spyne_zmq_interrupted_syscall.py", line 80, in run
    self.rpc_server.serve_once()
  File "/path/to/file/spyne_zmq_interrupted_syscall.py", line 22, in serve_once
    initial_ctx.in_string = [self.zmq_socket.recv()]
  File "zmq/backend/cython/socket.pyx", line 631, in zmq.backend.cython.socket.Socket.recv (zmq/backend/cython/socket.c:5775)
  File "zmq/backend/cython/socket.pyx", line 665, in zmq.backend.cython.socket.Socket.recv (zmq/backend/cython/socket.c:5575)
  File "zmq/backend/cython/socket.pyx", line 139, in zmq.backend.cython.socket._recv_copy (zmq/backend/cython/socket.c:1728)
  File "zmq/backend/cython/checkrc.pxd", line 21, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/socket.c:6251)
    raise ZMQError(errno)
ZMQError: Interrupted system call
```

After that, the program freezes. The entire file which reproduces the error is [here](https://gist.github.com/8f196ca5d6d76aed1003). Any ideas how to fix it?

**Comment by plq** [comment]
Hey,

This is a question, so it should go to the mailing list or stackoverflow.

Not only that, but also this is highly specific to zeromq, as the exception is in zmq code. so I don't actually know the answer to this question.

**Comment by Pastafarianist** [comment]
I *think* I have stripped the Spyne wrapper off the exception. [This gist](https://gist.github.com/Pastafarianist/d18080bec84cc4704a73) contains code which throws the same exception without ever importing Spyne.

Looks like this is not your bug.

**Comment by Pastafarianist** [comment]
This *is* your bug. Please look at the latest revision [here](https://gist.github.com/Pastafarianist/d18080bec84cc4704a73/revisions).

I don't know what exactly happens beneath the hood, but if I create the context in the thread which will be doing `.recv()`, the exception is not thrown. Apparently, the solution is to move `context` creation from the top level to `__init__`, assuming that the server is created in the same thread as the one where it executes.

**Comment by plq** [comment]
:)

Thanks for your interest, I'll have a look at this next week.

**Comment by plq** [comment]
Perhaps setting the context to a thread-local variable should easily solve this?

**Comment by Pastafarianist** [comment]
Yes, that's what moving it to `__init__` would do (i.e. `self.context = zmq.Context()`), unless (like me) you intend to hack the `serve_forever` method to not actually block forever and pass things around between the threads a lot.
