### ISSUE TITLE
AssertionError in combination with Integer and JsonDocument

### ISSUE THREAD

**Issue by solartune** [arskom/spyne#547]
Hi again :)
I have troubles with integer incoming arguments when I use JsonDocument protocol.
So, when I use something like this
```
@rpc(Integer)
 def foo(ctx, my_int):
     pass

app = Application(
    [MyService],
    'smth',
    in_protocol=JsonDocument(validator='soft'),
    out_protocol=JsonDocument()
)
```
Then I have the next error
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/spyne/server/django.py", line 87, in __call__
    response = WsgiApplication.__call__(self, environ, start_response)
  File "/usr/local/lib/python3.6/site-packages/spyne/server/wsgi.py", line 244, in __call__
    return self.handle_rpc(req_env, start_response)
  File "/usr/local/lib/python3.6/site-packages/spyne/server/wsgi.py", line 356, in handle_rpc
    self.get_in_object(p_ctx)
  File "/usr/local/lib/python3.6/site-packages/spyne/server/_base.py", line 93, in get_in_object
    message=self.app.in_protocol.REQUEST)
  File "/usr/local/lib/python3.6/site-packages/spyne/protocol/dictdoc/hier.py", line 65, in deserialize
    self.validator)
  File "/usr/local/lib/python3.6/site-packages/spyne/protocol/dictdoc/hier.py", line 232, in _doc_to_object
    subinst = self._from_dict_value(k, member, v, validator)
  File "/usr/local/lib/python3.6/site-packages/spyne/protocol/dictdoc/hier.py", line 138, in _from_dict_value
    retval = self.from_unicode(cls, inst)
  File "/usr/local/lib/python3.6/site-packages/spyne/protocol/_inbase.py", line 238, in from_unicode
    assert isinstance(string, str)
AssertionError
```
This trouble occur only if I use Integer and JsonDocument together.
Spyne version is 2.12.14

Thanks.

**Comment by kaywitt** [comment]
Experiencing the same issue for Floats.

```
@srpc(Array(Double), _returns=Double)
def predict_ref_model(params=[]):
    pass

application = Application([PybedictorService],
                          tns='spyne.examples.hello',
                          in_protocol=JsonDocument(validator='soft'),
                          out_protocol=JsonDocument())
```

```
Traceback (most recent call last):
  File "/home/kaywit/.local/lib/python3.5/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/home/kaywit/.local/lib/python3.5/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/kaywit/.local/lib/python3.5/site-packages/twisted/python/context.py", line 87, in callWithContext
    self.contexts.pop()
  File "/home/kaywit/.local/lib/python3.5/site-packages/twisted/web/wsgi.py", line 522, in run
    self.started = True
--- <exception caught here> ---
  File "/home/kaywit/.local/lib/python3.5/site-packages/twisted/web/wsgi.py", line 497, in run
    appIterator = self.application(self.environ, self.startResponse)
  File "/home/kaywit/.local/lib/python3.5/site-packages/spyne/server/wsgi.py", line 244, in __call__
    return self.handle_rpc(req_env, start_response)
  File "/home/kaywit/.local/lib/python3.5/site-packages/spyne/server/wsgi.py", line 356, in handle_rpc
    self.get_in_object(p_ctx)
  File "/home/kaywit/.local/lib/python3.5/site-packages/spyne/server/_base.py", line 93, in get_in_object
    message=self.app.in_protocol.REQUEST)
  File "/home/kaywit/.local/lib/python3.5/site-packages/spyne/protocol/dictdoc/hier.py", line 65, in deserialize
    self.validator)
  File "/home/kaywit/.local/lib/python3.5/site-packages/spyne/protocol/dictdoc/hier.py", line 236, in _doc_to_object
    subinst = self._from_dict_value(k, member, v, validator)
  File "/home/kaywit/.local/lib/python3.5/site-packages/spyne/protocol/dictdoc/hier.py", line 124, in _from_dict_value
    retval = self._doc_to_object(cls, inst, validator)
  File "/home/kaywit/.local/lib/python3.5/site-packages/spyne/protocol/dictdoc/hier.py", line 164, in _doc_to_object
    validator))
  File "/home/kaywit/.local/lib/python3.5/site-packages/spyne/protocol/dictdoc/hier.py", line 138, in _from_dict_value
    retval = self.from_unicode(cls, inst)
  File "/home/kaywit/.local/lib/python3.5/site-packages/spyne/protocol/_inbase.py", line 238, in from_unicode
    assert isinstance(string, str)
builtins.AssertionError: 

```

Also using spyne==2.12.14. 

In spyne.protocol._inbase.py the check
```
        if six.PY3:
            assert isinstance(string, str)

```
appearently receives as Float (as expected?) which cause the AssertionError.

**Comment by kaywitt** [comment]
Hi. The issue appears to be fixed in that version. Thank you for attending.
Note: There was a dependency on the lxml module that could be resolved by installing it. You may consider to take this module into the dependencies.

**Comment by plq** [comment]
> There was a dependency on the lxml module that could be resolved by installing it.

this is a bug. can you show the stack trace?

**Comment by kaywitt** [comment]
Sure.

======================================================================
ERROR: Failure: ModuleNotFoundError (No module named 'lxml')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kaywit/.local/lib/python3.6/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/home/kaywit/.local/lib/python3.6/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/kaywit/.local/lib/python3.6/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/kaywit/.local/lib/python3.6/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/python3.6/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kaywit/git/bisam/data-science/python/pybeutils/pybedictor/tests/test_rpc_system.py", line 16, in <module>
    from pybeutils.pybedictor.rpc_server import PybedictorService
  File "/home/kaywit/.local/lib/python3.6/site-packages/pluginbase.py", line 410, in plugin_import
    fromlist, level)
  File "/home/kaywit/git/bisam/data-science/python/pybeutils/pybedictor/rpc_server.py", line 27, in <module>
    from spyne import Application, srpc, ServiceBase, Unicode, Array, Double
  File "/home/kaywit/.local/lib/python3.6/site-packages/pluginbase.py", line 410, in plugin_import
    fromlist, level)
  File "/home/kaywit/.local/lib/python3.6/site-packages/spyne/__init__.py", line 55, in <module>
    from spyne.application import Application
  File "/home/kaywit/.local/lib/python3.6/site-packages/pluginbase.py", line 410, in plugin_import
    fromlist, level)
  File "/home/kaywit/.local/lib/python3.6/site-packages/spyne/application.py", line 28, in <module>
    from spyne.interface import Interface
  File "/home/kaywit/.local/lib/python3.6/site-packages/pluginbase.py", line 410, in plugin_import
    fromlist, level)
  File "/home/kaywit/.local/lib/python3.6/site-packages/spyne/interface/__init__.py", line 33, in <module>
    from spyne.interface.wsdl.wsdl11 import Wsdl11
  File "/home/kaywit/.local/lib/python3.6/site-packages/pluginbase.py", line 410, in plugin_import
    fromlist, level)
  File "/home/kaywit/.local/lib/python3.6/site-packages/spyne/interface/wsdl/__init__.py", line 25, in <module>
    from spyne.interface.wsdl.wsdl11 import Wsdl11
  File "/home/kaywit/.local/lib/python3.6/site-packages/pluginbase.py", line 410, in plugin_import
    fromlist, level)
  File "/home/kaywit/.local/lib/python3.6/site-packages/spyne/interface/wsdl/wsdl11.py", line 32, in <module>
    from lxml import etree
  File "/home/kaywit/.local/lib/python3.6/site-packages/pluginbase.py", line 410, in plugin_import
    fromlist, level)
ModuleNotFoundError: No module named 'lxml'

**Comment by plq** [comment]
fixed in 3bfb4bdb. thanks.

**Comment by kaywitt** [comment]
Which release will include this latest patch?

**Comment by plq** [comment]
The next one?

**Comment by kaywitt** [comment]
Yes sure. Thanks again for attending.
