### ISSUE TITLE
Python3.7 compatibility

### ISSUE THREAD

**Issue by mouadhkaabachi** [arskom/spyne#577]
I tried tu use spyne with python 3.7 and I got:

    Traceback (most recent call last):
    File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
    File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
    File "olapy/__main__.py", line 7, in <module>
    from core.services.xmla import runserver
    File "olapy/core/services/xmla.py", line 19, in <module>
    from spyne import AnyXml, Application, Fault, ServiceBase, rpc
    File "/home/moddoy/Envs/olapy_py37/lib/python3.7/site-packages/spyne/__init__.py", line 63, in <module>
    from spyne.server import ServerBase, NullServer
    File "/home/moddoy/Envs/olapy_py37/lib/python3.7/site-packages/spyne/server/__init__.py", line 23, in <module>
    from spyne.server.null import NullServer
    File "/home/moddoy/Envs/olapy_py37/lib/python3.7/site-packages/spyne/server/null.py", line 69
    self.service = _FunctionProxy(self, self.app, async=False)
                                                      ^
    SyntaxError: invalid syntax

**Comment by plq** [comment]
see https://pypi.org/project/spyne/2.13.2a0/
