### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by waqashamid** [arskom/spyne#587]
```
/spyne/server/wsgi.py", line 39, in parse_form_data
    raise import_error
NameError: name 'import_error' is not defined

```
I did not have `Werkzeug` installed which threw me this.

Installing that fixed it. 

However, this should have gracefully raised a `Werkzeug not found` exception. The code totally breaks when a dependency is unmet even though there is an import check.

This is definitely a bug.

**Comment by plq** [comment]
what version is this? stuff looks fine from here

**Comment by plq** [comment]
```
$ virtualenv -p python2.7 virt-2.7
Already using interpreter /usr/bin/python2.7
New python executable in /home/plq/src/arskom/ink/config-prod/virt-2.7/bin/python2.7
Also creating executable in /home/plq/src/arskom/ink/config-prod/virt-2.7/bin/python
Installing setuptools, pip, wheel...done.

$ source virt-2.7/bin/activate
(virt-2.7) $ python
Python 2.7.15 (default, Sep 24 2018, 01:23:17)
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> try:
...     from werkzeug.formparser import parse_form_data
... except ImportError as import_error:
...     def parse_form_data(*args, **kwargs):
...         raise import_error
...
>>> parse_form_data()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 5, in parse_form_data
ImportError: No module named werkzeug.formparser
>>>
```

**Comment by plq** [comment]
Excerpt taken from: https://github.com/arskom/spyne/blob/2_12/spyne/server/wsgi.py#L35

**Comment by plq** [comment]
ah. so that's a pytho3 thing. thanks for the heads-up.

**Comment by plq** [comment]
2.12.15 and 2.13.4-alpha released where this bug is fixed.
