### ISSUE TITLE
Not able to install spyne via pip: str has no attribute decode

### ISSUE THREAD

**Issue by cpwnd** [arskom/spyne#589]
```
$ pip install spyne
  Downloading https://files.pythonhosted.org/packages/cb/73/67e489bdfdf8ed9f927001595a1e57891b12e580fcfa9aa64b3c4df16a8a/spyne-2.12.15.tar.gz (439kB)
    100% |████████████████████████████████| 440kB 977kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-roci4pzn/spyne/setup.py", line 51, in <module>
        LONG_DESC += u"\n\n" + open('CHANGELOG.rst', 'r').read().decode('utf8')
    AttributeError: 'str' object has no attribute 'decode'
```
I'm able to install from branch `2_12` though.
Looks like the pypi version is not up to date.

**Comment by E-G-C** [comment]
Most likely incompatible with Python 3, use version  2.13.4a1 instead
pip install spyne==2.13.4a1

**Comment by plq** [comment]
This is supposed to solve this: https://pypi.org/project/spyne/2.12.16/

please reopen if not happy.
