### ISSUE TITLE
Failed to install via pipenv

### ISSUE THREAD

**Issue by amureki** [arskom/spyne#590]
Hi @plq !

I wonder what is the current state of the project? 

I am trying to install it via pipenv (currently recommended python packaging tool) and receiving the next error:
```
11:28 $ pipenv install spyne
Installing spyne…
Adding spyne to Pipfile's [packages]…
✔ Installation Succeeded
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
✘ Locking Failed!
Traceback (most recent call last):
  File "/Users/amureki/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pipenv/resolver.py", line 126, in <module>
    main()
  File "/Users/amureki/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pipenv/resolver.py", line 119, in main
    parsed.requirements_dir, parsed.packages)
  File "/Users/amureki/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pipenv/resolver.py", line 85, in _main
    requirements_dir=requirements_dir,
  File "/Users/amureki/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pipenv/resolver.py", line 69, in resolve
    req_dir=requirements_dir
  File "/Users/amureki/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pipenv/utils.py", line 726, in resolve_deps
    req_dir=req_dir,
  File "/Users/amureki/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pipenv/utils.py", line 480, in actually_resolve_deps
    resolved_tree = resolver.resolve()
  File "/Users/amureki/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pipenv/utils.py", line 385, in resolve
    results = self.resolver.resolve(max_rounds=environments.PIPENV_MAX_ROUNDS)
  File "/Users/amureki/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pipenv/patched/piptools/resolver.py", line 102, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/Users/amureki/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pipenv/patched/piptools/resolver.py", line 206, in _resolve_one_round
    for dep in self._iter_dependencies(best_match):
  File "/Users/amureki/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pipenv/patched/piptools/resolver.py", line 301, in _iter_dependencies
    dependencies = self.repository.get_dependencies(ireq)
  File "/Users/amureki/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 234, in get_dependencies
    legacy_results = self.get_legacy_dependencies(ireq)
  File "/Users/amureki/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 426, in get_legacy_dependencies
    results, ireq = self.resolve_reqs(download_dir, ireq, wheel_cache)
  File "/Users/amureki/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 297, in resolve_reqs
    results = resolver._resolve_one(reqset, ireq)
  File "/Users/amureki/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pipenv/patched/notpip/_internal/resolve.py", line 260, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/Users/amureki/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pipenv/patched/notpip/_internal/resolve.py", line 213, in _get_abstract_dist_for
    self.require_hashes
  File "/Users/amureki/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pipenv/patched/notpip/_internal/operations/prepare.py", line 294, in prepare_linked_requirement
    abstract_dist.prep_for_dist(finder, self.build_isolation)
  File "/Users/amureki/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pipenv/patched/notpip/_internal/operations/prepare.py", line 127, in prep_for_dist
    self.req.run_egg_info()
  File "/Users/amureki/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pipenv/patched/notpip/_internal/req/req_install.py", line 474, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/Users/amureki/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pipenv/patched/notpip/_internal/utils/misc.py", line 705, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pipenv.patched.notpip._internal.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in /var/folders/4c/kc26knyx2pb42z7xftg0_qjm0000gp/T/tmp5e42o_1vbuild/spyne/
File "/Users/amureki/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pipenv/resolver.py", line 126, in <module>
    main()
  File "/Users/amureki/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pipenv/resolver.py", line 119, in main
    parsed.requirements_dir, parsed.packages)
  File "/Users/amureki/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pipenv/resolver.py", line 85, in _main
    requirements_dir=requirements_dir,
  File "/Users/amureki/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pipenv/resolver.py", line 69, in resolve
    req_dir=requirements_dir
  File "/Users/amureki/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pipenv/utils.py", line 726, in resolve_deps
    req_dir=req_dir,
  File "/Users/amureki/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pipenv/utils.py", line 480, in actually_resolve_deps
    resolved_tree = resolver.resolve()
  File "/Users/amureki/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pipenv/utils.py", line 385, in resolve
    results = self.resolver.resolve(max_rounds=environments.PIPENV_MAX_ROUNDS)
  File "/Users/amureki/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pipenv/patched/piptools/resolver.py", line 102, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/Users/amureki/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pipenv/patched/piptools/resolver.py", line 206, in _resolve_one_round
    for dep in self._iter_dependencies(best_match):
  File "/Users/amureki/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pipenv/patched/piptools/resolver.py", line 301, in _iter_dependencies
    dependencies = self.repository.get_dependencies(ireq)
  File "/Users/amureki/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 234, in get_dependencies
    legacy_results = self.get_legacy_dependencies(ireq)
  File "/Users/amureki/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 426, in get_legacy_dependencies
    results, ireq = self.resolve_reqs(download_dir, ireq, wheel_cache)
  File "/Users/amureki/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 297, in resolve_reqs
    results = resolver._resolve_one(reqset, ireq)
  File "/Users/amureki/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pipenv/patched/notpip/_internal/resolve.py", line 260, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/Users/amureki/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pipenv/patched/notpip/_internal/resolve.py", line 213, in _get_abstract_dist_for
    self.require_hashes
  File "/Users/amureki/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pipenv/patched/notpip/_internal/operations/prepare.py", line 294, in prepare_linked_requirement
    abstract_dist.prep_for_dist(finder, self.build_isolation)
  File "/Users/amureki/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pipenv/patched/notpip/_internal/operations/prepare.py", line 127, in prep_for_dist
    self.req.run_egg_info()
  File "/Users/amureki/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pipenv/patched/notpip/_internal/req/req_install.py", line 474, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/Users/amureki/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pipenv/patched/notpip/_internal/utils/misc.py", line 705, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pipenv.patched.notpip._internal.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in /var/folders/4c/kc26knyx2pb42z7xftg0_qjm0000gp/T/tmp5e42o_1vbuild/spyne/
```

I tried to dig into the repository and found out that there is not test suite running properly and the latest build which did run was failing:
https://travis-ci.org/arskom/spyne/builds/470634855

I would like to know if it is anyhow usable and would be fixed, or you do not have any resources to continue on that project.

Best,
Rustem

**Comment by plq** [comment]
Hey, thanks for reaching out.

I've had enough of Travis and moved everything to Jenkins: https://jenkins.arskom.com.tr. To this day I have no idea why my testsuite fails on Travis and runs nicely everywhere else.

The project is active with the last release about a month ago: https://pypi.org/project/spyne/2.13.4a0/

Finally, I've got no idea about why the build is failing as the traceback you provided only says that the build has failed but doesn't say why.

Please use the mailing list if you want to chat further and reopen this issue if you can provide me with additional information.

Best,
