### ISSUE TITLE
ImportError: cannot import name 'ARRAY'

### ISSUE THREAD

**Issue by WorldException** [arskom/spyne#605]
I have simple error with import
SQLAlchemy==1.3.1
spyne==2.12.16

Traceback error
```
Traceback (most recent call last):
  File "/home/quick/projects/avtoformula/webserver.py", line 13, in <module>
    app = create_app()
  File "/home/quick/projects/avtoformula/web/__init__.py", line 50, in create_app
    from .balance import service_emex
  File "/home/quick/projects/avtoformula/web/balance/service_emex.py", line 6, in <module>
    from spyne.protocol.html import HtmlColumnTable
  File "/home/quick/projects/pyenvs/py3-avtoformula/lib/python3.6/site-packages/spyne/protocol/html/__init__.py", line 25, in <module>
    from spyne.protocol.html._base import HtmlBase
  File "/home/quick/projects/pyenvs/py3-avtoformula/lib/python3.6/site-packages/spyne/protocol/html/_base.py", line 27, in <module>
    from spyne.protocol.cloth import XmlCloth
  File "/home/quick/projects/pyenvs/py3-avtoformula/lib/python3.6/site-packages/spyne/protocol/cloth/__init__.py", line 24, in <module>
    from spyne.protocol.cloth._base import XmlCloth
  File "/home/quick/projects/pyenvs/py3-avtoformula/lib/python3.6/site-packages/spyne/protocol/cloth/_base.py", line 34, in <module>
    from spyne.protocol.cloth.to_parent import ToParentMixin
  File "/home/quick/projects/pyenvs/py3-avtoformula/lib/python3.6/site-packages/spyne/protocol/cloth/to_parent.py", line 38, in <module>
    from spyne.util.web import log_repr
  File "/home/quick/projects/pyenvs/py3-avtoformula/lib/python3.6/site-packages/spyne/util/web.py", line 49, in <module>
    from spyne.store.relational import PGFileJson
  File "/home/quick/projects/pyenvs/py3-avtoformula/lib/python3.6/site-packages/spyne/store/relational/__init__.py", line 25, in <module>
    from spyne.store.relational._base import add_column
  File "/home/quick/projects/pyenvs/py3-avtoformula/lib/python3.6/site-packages/spyne/store/relational/_base.py", line 51, in <module>
    from spyne.store.relational.simple import PGLTree
  File "/home/quick/projects/pyenvs/py3-avtoformula/lib/python3.6/site-packages/spyne/store/relational/simple.py", line 23, in <module>
    from sqlalchemy.dialects.postgresql.base import ischema_names, PGTypeCompiler, ARRAY
ImportError: cannot import name 'ARRAY'
```

Solution
```bash
patch /usr/local/lib/python2.7/site-packages/spyne/store/relational/simple.py ${PWD}/docker/spyne_patch.txt
```
spyne_patch.txt
```python
--- /usr/local/lib/python2.7/site-packages/spyne/store/relational/simple.py	2017-06-13 08:59:03.000000000 +0000
+++ pgsimple.py	2017-06-13 09:32:43.440087721 +0000
@@ -20,7 +20,8 @@
 from sqlalchemy import sql
 from sqlalchemy.ext.compiler import compiles
 from sqlalchemy.dialects.postgresql.base import PGUuid
-from sqlalchemy.dialects.postgresql.base import ischema_names, PGTypeCompiler, ARRAY
+from sqlalchemy.dialects.postgresql.base import ischema_names, PGTypeCompiler
+from sqlalchemy.dialects.postgresql.array import ARRAY
 from sqlalchemy.sql.sqltypes import Concatenable
 from sqlalchemy.sql.type_api import UserDefinedType
```
alternative patch
```python
try:
    from sqlalchemy.dialects.postgresql.base import ischema_names, PGTypeCompiler, ARRAY
except:
    from sqlalchemy.dialects.postgresql.base import ischema_names, PGTypeCompiler
    from sqlalchemy.dialects.postgresql.array import ARRAY
```

**Comment by plq** [comment]
hey, thanks a lot for the heads-up.

does #606 solve your problem? It looks like we were importing stuff too deep from the sqlalchemy source.

**Comment by WorldException** [comment]
Yes! this solved the problem
