### ISSUE TITLE
RuntimeError: generator raised StopIteration

### ISSUE THREAD

**Issue by jingz** [arskom/spyne#613]
I am trying to bind Spyne with Flask.
My machine running `python 3.7`
And `spyne` spyne-2.13.10a0
and I bind spyne wsgi app with flask

so I set up Spyne as

```python
import ...

def create_spyne_app():
    from .controllers.soap.hello_service import HelloWorldService

    # from soap to soap
    return WsgiApplication(
               Application([HelloWorldService], tns='spyne.example.flask',
                   in_protocol=Soap11(validator='lxml'),
                   out_protocol=Soap11()
           ))

... code

    app.wsgi_app = DispatcherMiddleware(app.wsgi_app, {
        "/soap": create_spyne_app(),
        })
... code
```

When started `flask run`

```sh
Traceback (most recent call last):
  File "/Users/jing/work/cdctbank/venv/lib/python3.7/site-packages/spyne-2.13.10a0-py3.7.egg/spyne/util/toposort.py", line 36, in toposort2
    raise StopIteration()
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/jing/work/cdctbank/venv/bin/flask", line 10, in <module>
    sys.exit(main())
  File "/Users/jing/work/cdctbank/venv/lib/python3.7/site-packages/flask/cli.py", line 906, in main
    cli.main(args=args, prog_name=name)
  File "/Users/jing/work/cdctbank/venv/lib/python3.7/site-packages/flask/cli.py", line 569, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/Users/jing/work/cdctbank/venv/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/jing/work/cdctbank/venv/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/jing/work/cdctbank/venv/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/jing/work/cdctbank/venv/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/jing/work/cdctbank/venv/lib/python3.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/Users/jing/work/cdctbank/venv/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/jing/work/cdctbank/venv/lib/python3.7/site-packages/flask/cli.py", line 779, in run_command
    app = DispatchingApp(info.load_app, use_eager_loading=eager_loading)
  File "/Users/jing/work/cdctbank/venv/lib/python3.7/site-packages/flask/cli.py", line 300, in __init__
    self._load_unlocked()
  File "/Users/jing/work/cdctbank/venv/lib/python3.7/site-packages/flask/cli.py", line 324, in _load_unlocked
    self._app = rv = self.loader()
  File "/Users/jing/work/cdctbank/venv/lib/python3.7/site-packages/flask/cli.py", line 386, in load_app
    raise_if_not_found=False)
  File "/Users/jing/work/cdctbank/venv/lib/python3.7/site-packages/flask/cli.py", line 236, in locate_app
    __import__(module_name)
  File "/Users/jing/work/cdctbank/wsgi.py", line 3, in <module>
    app = create_app()
  File "/Users/jing/work/cdctbank/application/__init__.py", line 58, in create_app
    "/soap": create_spyne_app(),
  File "/Users/jing/work/cdctbank/application/__init__.py", line 43, in create_spyne_app
    out_protocol=Soap11()
  File "/Users/jing/work/cdctbank/venv/lib/python3.7/site-packages/spyne-2.13.10a0-py3.7.egg/spyne/application.py", line 131, in __init__
    self.in_protocol.set_app(self)
  File "/Users/jing/work/cdctbank/venv/lib/python3.7/site-packages/spyne-2.13.10a0-py3.7.egg/spyne/protocol/xml.py", line 413, in set_app
    xml_schema.build_validation_schema()
  File "/Users/jing/work/cdctbank/venv/lib/python3.7/site-packages/spyne-2.13.10a0-py3.7.egg/spyne/interface/xml_schema/_base.py", line 207, in build_validation_schema
    self.build_schema_nodes(with_schema_location=True)
  File "/Users/jing/work/cdctbank/venv/lib/python3.7/site-packages/spyne-2.13.10a0-py3.7.egg/spyne/interface/xml_schema/_base.py", line 135, in build_schema_nodes
    for cls in chain.from_iterable(toposort2(self.interface.deps)):
RuntimeError: generator raised StopIteration
```

Now I check at toposort2.py

```python
def toposort2(data):
    if len(data) == 0:
        raise StopIteration()  # <-- Error Raised from this line

    for k, v in data.items():
        v.discard(k) # Ignore self dependencies
```

and now I fix with `return` not sure this is the right solution.

**Comment by plq** [comment]
hey, thanks for the report.

Looks related to this: https://stackoverflow.com/questions/51700960/runtimeerror-generator-raised-stopiteration-every-time-i-try-to-run-app

Your fix seems to be the correct one.

**Comment by plq** [comment]
already fixed.
