### ISSUE TITLE
AttributeError: type object 'ComplexModelMeta' has no attribute 'get_flat_type_info'

### ISSUE THREAD

**Issue by plq** [arskom/spyne#626]
Copying the the [question from StackOverflow](https://stackoverflow.com/questions/58916378/complex-type-as-method-parameter-in-spyne-framework):

---

I am trying to implement SOAP server in Python (v 3.6) by Spyne framewok. I have proposed WSDL file with document style and some functions. These functions have complex type as parameters. I installed lates Spyne 2.12.16 and according Spyne doc. I wrote following code: 

```python
class PublicationDto(ComplexModel):

    publicationId = Integer
    title = String
    year = Short
    authors = String
    documentName = String

class PublicationService(ServiceBase):

    @rpc(
        PublicationDto)
    def add_publication(self, publication):
        print(publication)

    @rpc(
        _returns=Iterable(PublicationDto))
    def get_publications(self):
        return publication_service.get_publication_all()

application = Application([PublicationService], 'spyne.examples.hello.soap',
                          in_protocol=Soap11(validator=None),
                          out_protocol=Soap11())

wsgi_application = WsgiApplication(application)

if __name__ == '__main__':

    from wsgiref.simple_server import make_server

    server = make_server('127.0.0.1', 8000, wsgi_application)
    server.serve_forever()
```

The function **get_publications** work fine and server returns me correct data. But there is a problem with **add_publication** the Spyne cannot correct process it. It returns following error:

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "/server/venv/lib/python3.6/site-packages/spyne/server/wsgi.py", line 244, in __call__
    return self.handle_rpc(req_env, start_response)
  File "/server/venv/lib/python3.6/site-packages/spyne/server/wsgi.py", line 356, in handle_rpc
    self.get_in_object(p_ctx)
  File "/server/venv/lib/python3.6/site-packages/spyne/server/_base.py", line 93, in get_in_object
    message=self.app.in_protocol.REQUEST)
  File "/server/venv/lib/python3.6/site-packages/spyne/protocol/soap/soap11.py", line 263, in deserialize
    ctx.in_object = self.from_element(ctx, body_class, ctx.in_body_doc)
  File "/server/venv/lib/python3.6/site-packages/spyne/protocol/xml.py", line 443, in from_element
    return handler(ctx, cls, element)
  File "/server/venv/lib/python3.6/site-packages/spyne/protocol/xml.py", line 923, in complex_from_element
    value = self.from_element(ctx, member, c)
  File "/server/venv/lib/python3.6/site-packages/spyne/protocol/xml.py", line 443, in from_element
    return handler(ctx, cls, element)
  File "/server/venv/lib/python3.6/site-packages/spyne/protocol/xml.py", line 885, in complex_from_element
    inst = cls.get_deserialization_instance()
  File "/server/venv/lib/python3.6/site-packages/spyne/model/complex.py", line 931, in get_deserialization_instance
    return cls()
  File "/server/venv/lib/python3.6/site-packages/spyne/model/complex.py", line 781, in __init__
    fti = cls.get_flat_type_info(cls)
AttributeError: type object 'ComplexModelMeta' has no attribute 'get_flat_type_info'

```
It I use primitive types as parameters insted of complex, everything is ok.

I tried also install alpha version ** spyne==2.13.11a0** and run example code from distribution tar.gz called **complex.py** And the previous mentioned error still persist:

```
AttributeError: type object 'ComplexModelMeta' has no attribute 'get_flat_type_info'
```

So I must doing something wrong ... I appreciate any help. Thanks

Edit: 

1) There is a similar problem, but with no solution
https://stackoverflow.com/questions/51588986/spyne-complexmodelmeta-prepare-returns-empty-ordered-dictionary-in-python-3 

2) I find out, the problem relats with returns type to (not only input), but when you once use the type with wrapped class like **Iterable** problem is gone.

---

**Comment by plq** [comment]
I can't reproduce this. I modified your code to be a self-contained script which also shows some debugging info. Can you please run it and post the output here?

```python
import logging
logging.basicConfig(level=logging.DEBUG)
logging.getLogger("spyne.protocol.xml").setLevel(logging.DEBUG)

from spyne import ComplexModel, Integer, String, Short, ServiceBase, rpc, \
    Iterable, Application
from spyne.server.wsgi import WsgiApplication
from spyne.protocol.soap import Soap11


class PublicationDto(ComplexModel):
    publicationId = Integer
    title = String
    year = Short
    authors = String
    documentName = String


class PublicationService(ServiceBase):
    @rpc(PublicationDto)
    def add_publication(ctx, publication):
        print(publication)

    @rpc(_returns=Iterable(PublicationDto))
    def get_publications(ctx):
        return [
            PublicationDto(
                publicationId=5,
                title="title",
                year=32767,
                authors="authors",
                documentName="documentName",
            )
        ]


application = Application([PublicationService], 'spyne.examples.hello.soap',
                          in_protocol=Soap11(validator=None),
                          out_protocol=Soap11())


wsgi_application = WsgiApplication(application)


if __name__ == '__main__':
    from wsgiref.simple_server import make_server
    server = make_server('127.0.0.1', 8000, wsgi_application)
    logging.info("listening on 127.0.0.1:8000")
    server.serve_forever()
```

**Comment by Fleury93** [comment]
I seems now it is works. It is apparently because I did not run that without debug mode before. No when I simply run it it works, its odd.

So thanks for your help. I am ashamed :D

**Comment by plq** [comment]
It doesn't have anything to do with debug logging. Anyway, reopen if you can help me reproduce it.

**Comment by bifshteks** [comment]
It does have smth with Intelij Idea (I use PyCharm). When I run my code without debug mode - all __cls__ vars in `File "/home/artem/djsm/venv/lib/python3.6/site-packages/spyne/model/complex.py", line 783, in __init__
    fti = cls.get_flat_type_info(cls)` are of type <class 'spyne.model.complex.ComplexModelMeta'>, but when I turn debugger on at some point one var has type <class 'spyne.util.meta.Prepareable'>, that triggers the error.

python 3.6.9, spyne 2.12.16, pycharm 2019.3.4
