### ISSUE TITLE
python 3.7.3: Invalid syntax when importing spyne.

### ISSUE THREAD

**Issue by pcs3rd** [arskom/spyne#641]
Currently trying to use spyne. When trying to import it, python returns the following error:
```
Python 3.7.3 (default, Dec 20 2019, 18:57:59) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import spyne
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/.local/lib/python3.7/site-packages/spyne/__init__.py", line 63, in <module>
    from spyne.server import ServerBase, NullServer
  File "/home/pi/.local/lib/python3.7/site-packages/spyne/server/__init__.py", line 23, in <module>
    from spyne.server.null import NullServer
  File "/home/pi/.local/lib/python3.7/site-packages/spyne/server/null.py", line 69
    self.service = _FunctionProxy(self, self.app, async=False)
                                                      ^
SyntaxError: invalid syntax
```  

>>>

**Comment by bgermann** [comment]
This is fixed with e9b1f3bb85d6 which is available in 2.13.3-alpha. Unfortunately, Python 3 support was never published in a stable release.

**Comment by pcs3rd** [comment]
So, do I just have to install from the repository then or will this get built into a stable release build?

**Comment by bgermann** [comment]
I would install the latest beta version from PyPI. I do not know anything about spyne-flask.

**Comment by pcs3rd** [comment]
Thank you!
